#+TITLE: Connor Gallopo's Emacs Configuration

* Package Management

** Repositories

  Setup the package repositories. I use the canonical GNU repository, as
  well as a handful of community supported repositories.

  #+BEGIN_SRC emacs-lisp
    (add-to-list 'package-archives '("melpa" . "http://melpa.org/packages/"))
    (add-to-list 'package-archives '("marmalade" . "https://marmalade-repo.org/packages/"))
    (add-to-list 'package-archives '("org" . "http://orgmode.org/elpa/"))
  #+END_SRC

** =use-package=

  Make sure use-package is installed. use-package is used to install,
  and load/configure packages lazily. This should be the only package
  that needs to be explicitly installed via the =package.el= manager.

  #+BEGIN_SRC emacs-lisp
    (unless (package-installed-p 'use-package)
      (package-refresh-contents)
      (package-install 'use-package)
      (require 'use-package))
  #+END_SRC

* Path Management

  The path must explicitly be loaded into Emacs on Mac OS X. NOTE: this
  happens automatically on Linux.

  #+BEGIN_SRC emacs-lisp
    (use-package exec-path-from-shell
      :if (memq window-system '(mac ns x))
      :ensure t
      :config
      (exec-path-from-shell-initialize)
      (setq exec-path (cons "/opt/local/bin" exec-path))
      (setenv "PATH" (concat "/opt/local/bin:" (getenv "PATH"))))
  #+END_SRC

* UI Preferences

** Set font size

   I like a slightly larger than usual font. This little helper allows
   me to describe and set the font size in "points"

   #+BEGIN_SRC emacs-lisp
     (defun set-font-size (points)
       (interactive "n Font Size in Points: ")
       (cl-flet ((font-height (points) (* 10 points)))
         (set-face-attribute 'default nil :height (font-height points))))

     (set-font-size 16)
   #+END_SRC

** Hide emacs startup message

   I don't find the emacs welcome message useful, so prevent it on startup.

   #+BEGIN_SRC emacs-lisp
     (setq inhibit-startup-message t)
   #+END_SRC

** Initialize the color-theme

   I prefer the [[https://github.com/morhetz/gruvbox][Gruvbox]] color theme

   #+BEGIN_SRC emacs-lisp  (use-package gruvbox-theme
     (use-package gruvbox-theme
       :ensure t
       :config
       (load-theme 'gruvbox-dark-soft t))
   #+END_SRC

** Disable menu, toolbar, and scrollbar UI elements

   I don't use the menu or scrollbar UI elements so I disable them to
   get back some screen real estate

   #+BEGIN_SRC emacs-lisp
     (use-package menu-bar
       :commands menu-bar-mode
       :init (menu-bar-mode -1))

     (use-package tool-bar
       :commands tool-bar-mode
       :init (tool-bar-mode -1))

     (use-package scroll-bar
       :commands scroll-bar-mode
       :init
       (scroll-bar-mode -1)
       (when (fboundp 'horizontal-scroll-bar-mode)
   (horizontal-scroll-bar-mode -1)))
   #+END_SRC

** Line Wrapping

   Use soft line wrapping for text modes

   #+BEGIN_SRC emacs-lisp
     (add-hook 'markdown-mode-hook 'visual-line-mode)
     (add-hook 'org-mode-hook 'visual-line-mode)
   #+END_SRC

* Buffer preferences

** Prefer two space character indentation

   In my experience, whitespace is more portable than <tab>
   characters. As such, I use two white-space characters for
   indentation.

   #+BEGIN_SRC emacs-lisp
     (setq-default tab-width 2)
     (setq-default indent-tabs-mode nil)
   #+END_SRC

** Ensure that files end with a newline character

   This tends to be part of the code-style of many organizations for
   which I do work and it doesn't hurt to make sure that the last
   character in any file is a \n character so I make it the default.

   #+BEGIN_SRC emacs-lisp
     (setq require-final-newline t)
   #+END_SRC

** Remove trailing whitespace on save

   Extra end-of-line whitespace bugs me, but I'm also prone to
   introducing it so automatically trim trailing whitespace when a
   buffer is saved.

   #+BEGIN_SRC emacs-lisp
     (add-hook 'before-save-hook 'whitespace-cleanup)
   #+END_SRC

** Show and match bracket pairs

   Highligh matching brackets and when I open a bracket, autmaically
   close it for me:

   For example: [], (), {}, et cetera.

   #+BEGIN_SRC emacs-lisp
     (show-paren-mode t)
     (electric-pair-mode t)
   #+END_SRC

** Allow deletion of highlighted regions

   I like to be able to select a region and delete it.

   #+BEGIN_SRC emacs-lisp
     (delete-selection-mode t)
   #+END_SRC

** Undo

   I've oft found the default Emacs undo functionality gets a bit
   confusing when undo/redo comes into play. [[https://github.com/terryfinn][Terry]] agrees and uses undo-tree to get around this

   #+BEGIN_SRC emacs-lisp
     (use-package undo-tree
       :ensure t
       :init
       (global-undo-tree-mode))
   #+END_SRC

* Auto-save and Backups Behavior

** Centralize auto-save and backup locations

  I like to keep all of Emacs' auto-generated saves and backups tidily
  in a central place rather than littering the filesystem. Here I tell
  emacs to redirect the generated files to a known directory when it
  auto-saves.

  #+BEGIN_SRC emacs-lisp
    (make-directory "~/.emacs.d/autosaves/" t)
    (make-directory "~/.emacs.d/backups/" t)

    (setq auto-save-file-name-transforms
    (quote ((".*" "~/.emacs.d/autosaves/\\1" t))))
    (setq backup-directory-alist
    (quote ((".*" . "~/.emacs.d/backups/"))))
  #+END_SRC

** Centralize =tramp= backups

   For the same reasons as auto-saves and backups, I keep backups from
   Tramp mode in the same centralized location.

   #+BEGIN_SRC emacs-lisp
     (setq tramp-backup-directory-alist backup-directory-alist)
   #+END_SRC

** Enable backups for files under version control

   Just because the file is under version control does not mean I
   don’t care about backups. Lets make sure they are still getting
   backed up.

   #+BEGIN_SRC emacs-lisp
     (setq vc-make-backup-files t)
   #+END_SRC

** Save on lose focus

   When I leave emacs or change a buffer, auto-save all open buffers.

   #+BEGIN_SRC emacs-lisp
     (use-package super-save
       :ensure t
       :init
       (super-save-mode t)
       (setq super-save-auto-save-when-idle t))
   #+END_SRC

* Better scrolling

** Make scrolling smoother and scroll one line at a time

   The default emacs scrolling behavior can be difficult to use; the text
   jumps too much too fast. This should make scrolling a little bit more
   smooth when in GUI emacs.

   #+BEGIN_SRC emacs-lisp
     (when window-system
       (setq mouse-wheel-scroll-amount '(1 ((shift) . 1)))
       (setq mouse-wheel-progressive-speed nil)
       (setq mouse-wheel-follow-mouse 't)
       (setq scroll-step 1))
   #+END_SRC

* Syntax checking

  I generally find checking syntax and structure useful, and flycheck
  does this well, and has many plugins that I can enable in other
  modes, so lets make sure it is installed and enabled here.

  #+BEGIN_SRC emacs-lisp
    (use-package flycheck
      :ensure t
      :init
      (add-hook 'after-init-hook #'global-flycheck-mode)
      :config
      (setq-default flycheck-disabled-checkers (append flycheck-disabled-checkers '(javascript-jshint)))
      (flycheck-add-mode 'javascript-eslint 'js-mode)
      (flycheck-add-mode 'javascript-eslint 'js2-mode)
      (flycheck-add-mode 'javascript-eslint 'rjsx-mode)
      (setq flycheck-javascript-eslint-executable "node_modules/.bin/eslint")
      (setq flycheck-ruby-rubocop-executable "bin/rubocop"))
  #+END_SRC

* Spell Checking

  I am prone to typos. Enable flyspell in textual contexts to help
  catch the times where I don't quite English so well.

  #+BEGIN_SRC emacs-lisp
    (use-package flyspell
      :diminish flyspell-mode
      :commands (flyspell-prog-mode flyspell-mode)
      :init
      (if (string-equal system-type "darwin") (setq ispell-program-name "/usr/local/bin/aspell"))
      (add-hook 'ruby-mode-hook 'flyspell-prog-mode)
      (add-hook 'markdown-mode-hook 'flyspell-mode)
      (add-hook 'org-mode-hook 'flyspell-mode)
      (add-hook 'text-mode-hook 'flyspell-mode))


  #+END_SRC

* Auto Complete

  I find auto completion allows the speed of my hands to more closely
  match the speed of my brain and avoids typos. I used to use
  =auto-complete=, but a friend has convinced me to try =company-mode=
  so let's give it a shot.

  #+BEGIN_SRC emacs-lisp
    (use-package company
      :ensure t
      :diminish company-mode
      :bind ("C-:" . company-complete)
      :init
      (setq company-dabbrev-ignore-case t
      company-show-numbers t)
      (add-hook 'after-init-hook 'global-company-mode)
      :config
      (add-to-list 'company-backends 'company-math-symbols-unicode))
  #+END_SRC

* CSS

  Seems css-mode ignores global indentations settings, so lets specifically set that now.

  #+BEGIN_SRC emacs-lisp
    (use-package css-mode
      :ensure t
      :init
      (setq css-indent-offset 2))
  #+END_SRC

* Gist

  My memory is terrible. To supplement I tend to keep notes in
  [[gist.github.com][gists]]. This makes it so that I can work with my gists from within
  the emacs editor.

  NOTE: User authentication information is stored elsewhere as
  described in the [[https://github.com/defunkt/gist.el#gistel----emacs-integration-for-gistgithubcom][gist.el]] documentation.

  #+BEGIN_SRC emacs-lisp
    (use-package gist
      :ensure t)
  #+END_SRC

* Git

** Magit

   Magit is a staple of my interaction with git. Its fast, and
   intuitive interface allow me to quickly complete interactions with
   the git Version Control System without lots of repetitive typing or
   cryptic aliases.

   #+BEGIN_SRC emacs-lisp
     (use-package magit
       :ensure t
       :commands magit-status magit-blame
       :bind ("C-x g" . magit-status))
   #+END_SRC

** Forge

   [[https://github.com/magit/forge][Forge]] extends Magit to work with Github and Gitlab - pull requests,
   tokens, etc.

   #+BEGIN_SRC emacs-lisp
     (use-package forge
       :ensure t)
   #+END_SRC

* Markdown

  I work with Github a lot. I work with other developers a lot. Not
  many of those developers use =org-mode= -- which is my preferred
  format for documentation and note taking. As such, I author shared
  documentation in Markdown as it seems to be more portable and
  completely unavoidable.

  #+BEGIN_SRC emacs-lisp
    (use-package markdown-mode
      :ensure t)
  #+END_SRC

* Org

  I use =org-mode= a lot. For note taking, formatting textual data
  with tables, and even writing notes to future versions of myself
  about my emacs configuration (Hi, future me! You handsome devil.)

  When using bullet lists, the below configuration make it easier to
  see nested contexts by using different line heights for each
  indentation level.

  #+BEGIN_SRC emacs-lisp
    (use-package org
      :ensure org-plus-contrib
      :init
      (package-initialize)
      :config
      (set-face-attribute 'org-level-1 nil :height 2.0)
      (set-face-attribute 'org-level-2 nil :height 1.75)
      (set-face-attribute 'org-level-3 nil :height 1.65)
      (set-face-attribute 'org-level-4 nil :height 1.55)
      (set-face-attribute 'org-level-5 nil :height 1.5)
      (setq org-todo-keywords
            '((sequence "TODO"
                        "STARTED"
                        "|"
                        "DONE")))
      (setq org-todo-keyword-faces
            '(("TODO" :foreground "green" :weight bold)
              ("STARTED" :foreground "orange" :weight bold)
              ("DONE" :foreground "red" :weight bold))))
  #+END_SRC

  This takes org-mode bullet lists one step farther. It renders
  indentation level bullet headers so they look like a single bullet
  at the correct indentation level. The '*' characters are still
  there, but hidden through the magic of colors.

  #+BEGIN_SRC emacs-lisp
    (use-package org-bullets
      :ensure t
      :commands (org-bullets-mode)
      :init
      (add-hook 'org-mode-hook 'org-bullets-mode)
      (require 'ox-md))
  #+END_SRC

* Regular Expressions

  #+BEGIN_SRC emacs-lisp
    (use-package re-builder
      :ensure t
      :config
      (setq reb-re-syntax 'string))
  #+END_SRC

* Ruby

** ruby-mode

   Associate =ruby-mode= with ruby-ish files -- like Gemfiles,
   Rakefiles, etc.

   Prevent emacs from writing the "Magic Encoding
   Comment" at the top of source files which use exotic coding
   schemes.

   Do not indent new lines to context depth, rather use a standard
   indentation. For example, format indentations like:

   #+BEGIN_EXAMPLE
     def foo(
      bar:,
      baz:
     )
      ...
     end
   #+END_EXAMPLE

   not like this:

   #+BEGIN_EXAMPLE
     def foo(
      bar:,
      baz:
     )
      ...
     end
   #+END_EXAMPLE

   #+BEGIN_SRC emacs-lisp
     (use-package ruby-mode
       :ensure t
       :bind (
        ("C-c C-c" . xmp))
       :mode
       (("\\.rb$" . ruby-mode)
       ("\\.rake$" . ruby-mode)
       ("Rakefile$" . ruby-mode)
       ("\\.gemspec$" . ruby-mode)
       ("\\.ru$" . ruby-mode)
       ("Gemfile$" . ruby-mode)
       ("Guardfile$" . ruby-mode))
       :init
       (setq ruby-insert-encoding-magic-comment nil
       ruby-deep-indent-paren nil
       ruby-indent-tabs-mode nil)
       (add-hook 'ruby-mode 'superword-mode)
       :config
       (bind-key "M-<down>" 'ruby-forward-sexp)
       (bind-key "M-<up>" 'ruby-backward-sexp)
       (bind-key "C-c C-e" 'ruby-send-region))
   #+END_SRC

** rbenv

   I use [[http://rbenv.org/][rbenv]] to manage my ruby versions. Here I make emacs rbenv aware.

   #+BEGIN_SRC emacs-lisp
     (use-package rbenv
       :ensure t
       :init
       (setq rbenv-installation-dir (file-chase-links "/usr/local/opt/rbenv")))
  #+END_SRC

** ruby-end

   Similar to electric-paren, ruby-end takes care of automatically
   inserting end to close blocks, methods, and conditionals.

   #+BEGIN_SRC emacs-lisp
     (use-package ruby-end
       :ensure t)
   #+END_SRC

** rspec

   I, sometimes, like to run targeted groups of specs from within
   emacs. Here I make emacs aware of rspec and how to run groups of
   specs. This also enables debugging in emacs with tools like [[https://github.com/deivid-rodriguez/byebug][byebug]]
   and [[https://github.com/pry/pry][pry]].

   #+BEGIN_SRC emacs-lisp
     (use-package rspec-mode
       :ensure t
       :init
       (add-hook 'after-init-hook 'inf-ruby-switch-setup)
       :config
       (add-hook 'rspec-compilation-mode-hook
                 (lambda ()
                   (company-mode -1)
                   (make-local-variable 'compilation-scroll-output)
                   (setq compilation-scroll-output 'first-error))))
   #+END_SRC

** inf-ruby

   I want to be able to use the ruby REPL inside of emacs. This
   enables the "inferior ruby" mode

   #+BEGIN_SRC emacs-lisp
     (use-package inf-ruby
       :ensure t
       :init
       (add-hook 'ruby-mode-hook 'inf-ruby-minor-mode)
       :config
       (add-hook 'inf-ruby-mode-hook
                 (lambda ()
                   (company-mode -1))))
   #+END_SRC

** erb

   Use =web-mode= to edit ERB templates

   #+BEGIN_SRC emacs-lisp
     (use-package web-mode
       :ensure t
       :mode
       ("\\.erb\\'" . web-mode)
       :init
       (setq web-mode-markup-indent-offset 2))
   #+END_SRC

** YAML

   I mostly run into YAML when dealing with ruby configuration. This
   makes it easier to work with and format YAML.

   #+BEGIN_SRC emacs-lisp
     (use-package yaml-mode
       :ensure t)
   #+END_SRC

* SASS

  Prevent =sass-mode= from compiling sass files on save

  #+BEGIN_SRC emacs-lisp
    (use-package sass-mode
      :ensure t
      :init
      (setq-default scss-compile-at-save nil))
  #+END_SRC

* web-mode

  When working with HTML templates, let's use an indentation style
  that's consistent with other coding indentation rules.

   #+BEGIN_SRC emacs-lisp
     (use-package web-mode
       :ensure t
       :init
       (setq web-mode-markup-indent-offset 2)
       (setq web-mode-css-indent-offset 2)
       (setq web-mode-code-indent-offset 2)
       (setq web-mode-indent-style 2)
       (setq web-mode-block-padding 2))
   #+END_SRC
